name: Account linking - Incoming LDAP - conflicts OAuth error
authgear.yaml:
  override: |
    authentication:
      identities:
        - ldap
        - oauth
    identity:
      ldap:
        servers:
        - name: ldap-server-1
          url: ldap://127.0.0.1:8389
          base_dn: dc=authgear,dc=com
          search_filter_template: (uid={{.Username}})
          user_id_attribute_name: uid
    authentication_flow:
      signup_flows:
        - name: f1
          steps:
            - type: identify
              one_of:
              - identification: ldap
              - identification: oauth
before:
  - type: user_import
    user_import: google_user.json
  - type: custom_sql
    custom_sql:
      path: google_user.sql

steps:
  - action: "create"
    input: |
      {
        "type": "signup",
        "name": "f1"
      }
    output:
      result: |
        {
          "action": {
            "type": "identify"
          }
        }

  - action: input
    input: |
      {
        "identification": "ldap",
        "server_name": "ldap-server-1",
        "username": "mock",
        "password": "mockpassword"
      }
    output:
      error: |
        {
          "reason": "InvariantViolated",
          "info": {
            "cause": {
              "kind": "DuplicatedIdentity"
            }
          }
        }
